plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}
android {
    namespace 'com.wamid.trimblend'
    compileSdk 34
    defaultConfig {
        applicationId "com.wamid.trimblend"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
        vectorDrawables { useSupportLibrary true }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug { debuggable true }
    }
    buildFeatures { viewBinding true }
}
dependencies {
    implementation 'org.opencv:opencv-android:4.9.0'
}
